### ISSUE TITLE
Add option to specify custom proxy host and port

### ISSUE THREAD

**Issue by kwaaak** [AlyoshaVasilieva/luminous-ttv-ext#1] opened 2022-03-30 23:49 UTC
Thank you for creating this, it would be nice if the extension had basic settings to choose the proxy host and port.
The obvious use case would be running the proxy on a Raspberry Pi on the local network.
I have used `socat` to tunnel, but native would be even better.

Obviously, the server would also need a setting to listen on different interfaces.

**Comment by AlyoshaVasilieva** [comment] 2022-03-31 19:52
I'll take a look to see if I can do this. I've never given an extension an actual UI before.

I'll note that I don't plan on publishing this extension to the Chrome store, though, and (at least on my machine) Chrome occasionally removes the extension from my browser - that might wipe the setting and require redoing it.

The server part should be easy.

**Comment by AlyoshaVasilieva** [comment] 2022-04-01 00:25
Please try [v0.8.0](https://github.com/AlyoshaVasilieva/luminous-ttv-ext/releases/tag/v0.8.0) of the extension with [v0.4.3](https://github.com/AlyoshaVasilieva/luminous-ttv/releases/tag/v0.4.3) of the server. It works for me on Chrome using my desktop connecting to an Odroid-C2.

The extension code I wrote is awful but I'm not great at JS/browsers.

**Comment by kwaaak** [comment] 2022-04-05 03:04
Thanks, it's working.
Only problem, I am still getting ads with a RU proxy, to the point where I am now using the `Alternate Player for Twitch.tv` extension

**Comment by AlyoshaVasilieva** [comment] 2022-04-05 05:02
Alternately try running the server with "-c sg" for Singapore. I'll check on countries myself later.

**Comment by AlyoshaVasilieva** [comment] 2022-04-06 08:32
Can't reproduce ads with RU proxy, switching the extension on and off shows the expected ads with it disabled and no ads with it enabled. Closing this as the relevant request is implemented (if hackily).

**Closed as completed by AlyoshaVasilieva** 2022-04-06 08:32 UTC

**Comment by kwaaak** [comment] 2022-04-07 02:03
Thanks, Singapore was the ticket
